<?php

use Illuminate\Database\Seeder;

class UsersWithdrawHistoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users_withdraw_histories')->delete();
        
        \DB::table('users_withdraw_histories')->insert(array (
            0 => 
            array (
                'id' => 1,
                'top_id' => 0,
                'parent_id' => 0,
                'user_id' => 1,
                'username' => 'harriszhongdai',
                'is_tester' => 0,
                'rid' => '1',
                'order_id' => 'W201908291556024796',
                'card_id' => 0,
                'card_number' => '1234567894567856',
                'card_username' => '帝辛',
                'bank_sign' => 'BOCOM',
                'amount' => 10,
                'real_amount' => 0,
                'request_time' => 1567065362,
                'expire_time' => 0,
                'process_time' => 0,
                'process_day' => 0,
                'source' => 'web',
                'client_ip' => '103.42.94.10',
                'description' => '',
                'desc' => '',
                'status' => 0,
                'admin_id' => 0,
                'created_at' => '2019-08-29 15:56:02',
                'updated_at' => '2019-08-29 15:56:02',
            ),
            1 => 
            array (
                'id' => 2,
                'top_id' => 0,
                'parent_id' => 0,
                'user_id' => 1,
                'username' => 'harriszhongdai',
                'is_tester' => 0,
                'rid' => '1',
                'order_id' => 'W201908291558239201',
                'card_id' => 0,
                'card_number' => '1234567894567856',
                'card_username' => '帝辛',
                'bank_sign' => 'BOCOM',
                'amount' => 100,
                'real_amount' => 0,
                'request_time' => 1567065503,
                'expire_time' => 0,
                'process_time' => 0,
                'process_day' => 0,
                'source' => 'web',
                'client_ip' => '103.42.94.10',
                'description' => '',
                'desc' => '',
                'status' => 0,
                'admin_id' => 0,
                'created_at' => '2019-08-29 15:58:23',
                'updated_at' => '2019-08-29 15:58:23',
            ),
            2 => 
            array (
                'id' => 3,
                'top_id' => 0,
                'parent_id' => 0,
                'user_id' => 22,
                'username' => 'max777',
                'is_tester' => 0,
                'rid' => '22',
                'order_id' => 'W201908311612441954',
                'card_id' => 0,
                'card_number' => '2373733384838485000',
                'card_username' => '你今生',
                'bank_sign' => 'CMB',
                'amount' => 20,
                'real_amount' => 0,
                'request_time' => 1567239164,
                'expire_time' => 0,
                'process_time' => 0,
                'process_day' => 0,
                'source' => 'web',
                'client_ip' => '103.42.94.10',
                'description' => '',
                'desc' => '',
                'status' => 0,
                'admin_id' => 0,
                'created_at' => '2019-08-31 16:12:44',
                'updated_at' => '2019-08-31 16:12:44',
            ),
            3 => 
            array (
                'id' => 4,
                'top_id' => 0,
                'parent_id' => 0,
                'user_id' => 97,
                'username' => 'zxc',
                'is_tester' => 0,
                'rid' => '97',
                'order_id' => 'W201909021152513329',
                'card_id' => 0,
                'card_number' => '6222600260001072444',
                'card_username' => '123',
                'bank_sign' => 'ABC',
                'amount' => 20,
                'real_amount' => 0,
                'request_time' => 1567396371,
                'expire_time' => 0,
                'process_time' => 0,
                'process_day' => 0,
                'source' => 'web',
                'client_ip' => '103.42.94.10',
                'description' => '',
                'desc' => '',
                'status' => 0,
                'admin_id' => 0,
                'created_at' => '2019-09-02 11:52:51',
                'updated_at' => '2019-09-02 11:52:51',
            ),
            4 => 
            array (
                'id' => 5,
                'top_id' => 0,
                'parent_id' => 0,
                'user_id' => 97,
                'username' => 'zxc',
                'is_tester' => 0,
                'rid' => '97',
                'order_id' => 'W201909021153338033',
                'card_id' => 0,
                'card_number' => '6222600260001072444',
                'card_username' => '123',
                'bank_sign' => 'ABC',
                'amount' => 897058,
                'real_amount' => 0,
                'request_time' => 1567396413,
                'expire_time' => 0,
                'process_time' => 0,
                'process_day' => 0,
                'source' => 'web',
                'client_ip' => '103.42.94.10',
                'description' => '',
                'desc' => '',
                'status' => 0,
                'admin_id' => 0,
                'created_at' => '2019-09-02 11:53:33',
                'updated_at' => '2019-09-02 11:53:33',
            ),
            5 => 
            array (
                'id' => 10,
                'top_id' => 0,
                'parent_id' => 0,
                'user_id' => 81,
                'username' => 'max7777',
                'is_tester' => 0,
                'rid' => '81',
                'order_id' => 'W201909031516081524',
                'card_id' => 0,
                'card_number' => '6217001370027270875',
                'card_username' => 'bayern',
                'bank_sign' => 'CMB',
                'amount' => 20,
                'real_amount' => 0,
                'request_time' => 1567494968,
                'expire_time' => 0,
                'process_time' => 0,
                'process_day' => 0,
                'source' => 'web',
                'client_ip' => '103.104.16.186',
                'description' => '',
                'desc' => '',
                'status' => 0,
                'admin_id' => 0,
                'created_at' => '2019-09-03 15:16:08',
                'updated_at' => '2019-09-03 15:16:08',
            ),
            6 => 
            array (
                'id' => 11,
                'top_id' => 0,
                'parent_id' => 0,
                'user_id' => 81,
                'username' => 'max7777',
                'is_tester' => 0,
                'rid' => '81',
                'order_id' => 'W201909031525052080',
                'card_id' => 0,
                'card_number' => '6222600260001072444',
                'card_username' => '在',
                'bank_sign' => 'CCB',
                'amount' => 30000,
                'real_amount' => 0,
                'request_time' => 1567495505,
                'expire_time' => 0,
                'process_time' => 0,
                'process_day' => 0,
                'source' => 'web',
                'client_ip' => '103.42.94.10',
                'description' => '',
                'desc' => '',
                'status' => 0,
                'admin_id' => 0,
                'created_at' => '2019-09-03 15:25:05',
                'updated_at' => '2019-09-03 15:25:05',
            ),
            7 => 
            array (
                'id' => 12,
                'top_id' => 0,
                'parent_id' => 0,
                'user_id' => 81,
                'username' => 'max7777',
                'is_tester' => 0,
                'rid' => '81',
                'order_id' => 'W201909031525225654',
                'card_id' => 0,
                'card_number' => '6222600260001072444',
                'card_username' => '在',
                'bank_sign' => 'CCB',
                'amount' => 30000,
                'real_amount' => 0,
                'request_time' => 1567495522,
                'expire_time' => 0,
                'process_time' => 0,
                'process_day' => 0,
                'source' => 'web',
                'client_ip' => '103.42.94.10',
                'description' => '',
                'desc' => '',
                'status' => 0,
                'admin_id' => 0,
                'created_at' => '2019-09-03 15:25:22',
                'updated_at' => '2019-09-03 15:25:22',
            ),
            8 => 
            array (
                'id' => 13,
                'top_id' => 0,
                'parent_id' => 0,
                'user_id' => 81,
                'username' => 'max7777',
                'is_tester' => 0,
                'rid' => '81',
                'order_id' => 'W201909031528513614',
                'card_id' => 0,
                'card_number' => '6222600260001072444',
                'card_username' => '在',
                'bank_sign' => 'CCB',
                'amount' => 1111,
                'real_amount' => 0,
                'request_time' => 1567495731,
                'expire_time' => 0,
                'process_time' => 0,
                'process_day' => 0,
                'source' => 'web',
                'client_ip' => '103.42.94.10',
                'description' => '',
                'desc' => '',
                'status' => 0,
                'admin_id' => 0,
                'created_at' => '2019-09-03 15:28:51',
                'updated_at' => '2019-09-03 15:28:51',
            ),
        ));
        
        
    }
}